# No need to change the database file: just take the latest Postgresql image
db:
  image: postgres
  expose:
    - "5432"
# The algorithm node: rebuild from the recipe in the docker/scala folder
scala:
  build: ./docker/scala
  expose:
    - "8080"
# The web container running our Ruby server
# This is the only one with a port opened to the outside world!
ruby:
  build: .
  ports:
    - "80:80"
  links:
    - db
    - scala
